server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/book?useUnicode=true&characterEncodin=utf-8&serverTimezone=UTC
    username: root
    password: 373969383
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  
 